# Generated by Django 5.2.8 on 2025-11-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articul', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('measures', models.TextField()),
                ('price', models.IntegerField()),
                ('supplier', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('discount', models.IntegerField()),
                ('count', models.IntegerField()),
                ('description', models.TextField()),
                ('photo', models.CharField(max_length=100)),
            ],
        ),
    ]
